### ISSUE TITLE
"Form controls should be fully style-able"

### ISSUE THREAD

**Issue by fregante** [csstools/sanitize.css#115]
I think this rule leaves the page in a broken state and it's the only rule of this kind. 

If the purpose is resetting the style across browsers so it's easily styleable, then it needs further extension. For comparison, these are my "reset form elements" rules I built over time as I found inconsistencies:

``` scss
%os-element-reset {
    display: inline-block;
    overflow: visible;

    padding: 0;
    margin: 0;
    outline: 0;

    font: inherit;
    color: inherit;
    background-color: transparent;
    border: none;
    letter-spacing: inherit;

    text-transform: inherit;

    -webkit-font-smoothing: inherit;
    appearance: none;

    border-radius: 0;
    text-align: inherit;
}
%button-reset{
    @extend %os-element-reset;
    cursor: pointer;
    white-space: inherit;
    box-sizing: inherit;

    &::-moz-focus-inner {
        padding: 0;
        border: 0;
    }
}

%text-field-reset {
    @extend %os-element-reset;
    padding: .1em .2em 0;
    width: 100%;
    box-sizing: inherit;
    // &:focus {
    //  outline: 1px solid;
    // }
}
%textarea-reset {
    @extend %text-field-reset;
    resize: vertical;
}
```

But my first point still remains
