### ISSUE TITLE
Unset heading font-size

### ISSUE THREAD

**Issue by sundarj** [csstools/sanitize.css#123]
One thing I usually do is

```css
h1, h2, h3, h4, h5, h6 {
  font-size: 1em;
}
```

This means that you only need focus on whether a heading makes sense semantically, and it just takes the font size from the parent (usually a `<header>`). If you don't do this, you end up having to set a specific font size for the parents that take into account the heading's own font size. e.g. rather than the simple

```css
header {
  font-size: 2.5em;
}
```

you end up having to do

```css
header {
  font-size: 1.25em;
}
```

That's if the header in question should contain a h1 (if it can contain different headings at different times, you end up having to write `header h1, header h2 ....` - or using an additional class, of course)

There are plenty of ways people hack around this. See, for example: http://csswizardry.com/2012/02/pragmatic-practical-font-sizing-in-css/#double-stranded-heading-hierarchy.

I find that using heading elements merely for their semantics is more sensical.
