### ISSUE TITLE
figcaption

### ISSUE THREAD

**Issue by robsonsobral** [csstools/sanitize.css#126]
There's something always bothers me all over the web: the `figcaption` has no difference from the body text.

I strongly believe the `figcaption` should have at least the same `font-size` of `small`.

What do you think?

**Comment by jonathantneal** [comment]
Which styles would you suggest?

**Comment by robsonsobral** [comment]
Hi, @jonathantneal . Please, forgive my late answer. I missed this github notification.


The wikipedia uses:

```css
    line-height: 1.4em;
    padding: 3px;
    font-size: 94%;
```

The The Chicago Manual of Style says:

> Captions should be capitalized in sentence style (see 8.156), but formal titles of works included in captions should be capitalized in headline style (see 3.22). 

But I think a smaller font size is enough.

```css
figcaption {
    font-size: 80%; /* The same as used by `small` */
    line-height: inherit;
}

figcaption p,
figcaption small {
    font-size: 1em;
    margin: 0;
}
```

I usually use `font-size: 81.25%;`, the same as `13px`.

Thank you for your attention, @jonathantneal !

**Comment by jonathantneal** [comment]
I like this suggestion. I really appreciate that you did your research and can show examples of how it is used. I am in favor of adding this. I am confused by `figcaption p`; would `p` have changed the font size?

**Comment by robsonsobral** [comment]
Hi, @jonathantneal .

Thank you for your attention. I also like the idea of an italic font, but I guess it's too much a personal preference.

I added `p` because of it's margins. You're right. They should be two rules:

```css
figcaption p {
  margin: 0;
}
figcaption small {
  font-size: 1em;
}
```
