### ISSUE TITLE
button, html [type="button"], [type="reset"], [type="submit"] too specific.

### ISSUE THREAD

**Issue by dan-gamble** [csstools/sanitize.css#129]
Specifically (sorry) the `html [type="button"]` bit.

I have:
```css
.tst-Card_Expand {
  @apply --Font_15;

  font-weight: 500;
  text-transform: uppercase;

  /* Need to override sanitize */
  /* stylelint-disable */
  appearance: none !important;
  /* stylelint-enable */
  border: 0;
}
```

If i remove the `!important` i get: ![img](https://i.imgur.com/l1RMqpF.png)

Would it be possible to just use `[type="button"]`?
