### ISSUE TITLE
select default font-family is system-ui, should be inherit?

### ISSUE THREAD

**Issue by cloud-walker** [csstools/sanitize.css#142]
This is a question: after migrating from normalize to sanitize we noticed that in normalize we got:

```css
button,
input,
optgroup,
select,
textarea {
  font-family: sans-serif; /* 1 */
  font-size: 100%; /* 1 */
  line-height: 1.15; /* 1 */
  margin: 0; /* 2 */
}

```

while in sanitize we got:

```css
button,
input,
optgroup,
select,
textarea {
	margin: 0;
}


button,
input,
select,
textarea {
	color: inherit;
	font-size: inherit;
	line-height: inherit;
}
```

In my opinion the font-family too should be redefined using `font-family: inherit`, at least for the select tag.

Latest version of Chrome for example sets the default select font-family at `system-ui`

Here an experiment with jsbin: http://jsbin.com/sepigad/edit?html,css,output

Thanks in advance!
