### ISSUE TITLE
cursor: disabled is non-standard

### ISSUE THREAD

**Issue by cyco130** [csstools/sanitize.css#160]
The CSS rule to "change the cursor on disabled, not-editable, or otherwise inoperable elements in all browsers" is the following:

```css
[aria-disabled],
[disabled] {
  cursor: disabled;
}
```

But as far as I know `disabled` is not a valid value for the `cursor` property according to the standards. Maybe `not-allowed` was meant?
