### ISSUE TITLE
SVG fill rule breaks SVGs with fill="none"

### ISSUE THREAD

**Issue by davidmerrique** [csstools/sanitize.css#165]
Hi, when an SVG specifically has a `fill="none"` attribute, this library adds a fill.

It messes up some of the icons in https://feathericons.com/

I think the svg rule should be this:

```css
svg:not([fill="none"]) {
  fill: currentColor;
}
```

Thank you
