### ISSUE TITLE
Consider removing `touch-action: manipulation` rules in favor of a responsive meta tag

### ISSUE THREAD

**Issue by kripod** [csstools/sanitize.css#201]
As seen [on web.dev](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away) and observed [in a real project](https://github.com/logux/logux.io/pull/8), adding the following meta tag should be sufficient to bypass 300ms tap delays:

```html
<meta name="viewport" content="width=device-width">
```

I would suggest removing the following code [from sanitize.css](https://github.com/csstools/sanitize.css/blob/66dd0308db731b956f0f78501d1f1386fb952a25/sanitize.css#L498-L515), leaving a remark about the HTML-based technique in the readme:

```css
a,
area,
button,
input,
label,
select,
summary,
textarea,
[tabindex] {
  -ms-touch-action: manipulation; /* 1 */
  touch-action: manipulation; /* 2 */
}
```
