### ISSUE TITLE
Visible whitespace after `::content` appears in list items 

### ISSUE THREAD

**Issue by davidhund** [csstools/sanitize.css#203]
After [Announce `nav ol, nav ul` list semantics on Safari with VoiceOver ](https://github.com/csstools/sanitize.css/commit/5d86afd1d5c76414f086e97f276dae7d2ec2e7dd) I noticed whitespace showing up in list items.

<img width="465" alt="Screenshot 2020-09-02 at 11 23 04" src="https://user-images.githubusercontent.com/260518/91963949-da89a400-ed0e-11ea-8457-2da3576010f7.png">

The zero-width character introduced in the `content` property `before` list items seems to have the result of whitespace becoming significant and showing up. Simple test case at: https://codepen.io/davidhund/full/poyWRNJ

**Comment by mcecode** [comment]
[cssremedy](https://github.com/jensimmons/cssremedy) seems to fix this by adding `position: absolute;`

Relevant code snippet from cssremedy:

```css
/*
* 1. Add zero-width-space to prevent VoiceOver disable
* 2. Absolute position ensures no extra space
* See: https://unfetteredthoughts.net/2017/09/26/voiceover-and-list-style-type-none/
*/
nav li:before {
  content: "\200B";
  position: absolute;
}
```

Relevant file from cssremedy: <https://github.com/jensimmons/cssremedy/blob/master/css/reminders.css>.

I'm not sure if this will have unintended side effects elsewhere or if it's a sure fix but it did remove the space when I tried it in your codepen test case by adding:

```css
nav li:before {
  position: absolute;
}
```

at the end of the css file.
