### ISSUE TITLE
-ms-autohiding-scrollbar all the things

### ISSUE THREAD

**Issue by jonathantneal** [csstools/sanitize.css#31]
Check to see if `-ms-overflow-style` is inherited. If not, set it to inherit. This way, IE (and Edge?) get the nice appearing / disappearing scrollbars on the page and any overflowed element (like a `<pre>` with code) that we enjoy on Chrome, Firefox, and Safari.

``` css
* {
    -ms-overflow-style: inherit;
}

:root {
    -ms-overflow-style: -ms-autohiding-scrollbar;
}
```
