### ISSUE TITLE
Hide ::-ms-clear and ::-ms-reveal elements

### ISSUE THREAD

**Issue by thasmo** [csstools/sanitize.css#85]
Not sure if it fits the scope of sanitize.css, but what about hiding those by default?

``` css
input::-ms-clear,
input::-ms-reveal {
    display: none;
}
```
